name: Test White Box

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  jest-tests-Modelo:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install modules
        run: npm install
      - name: Run tests Jest on desktop viewport 🧪
        uses: cypress-io/github-action@v5
       
        with:
          command: npx jest saucedemo.spec.js 
                    
  